### ISSUE TITLE
Lectura de saldos.

### ISSUE THREAD

**Issue by rebelskvll** [zqu4rtz/FlipperApp-TuLlave#1]
Hola, un saludo. 
Estoy tratando de replicar este mismo concepto de leer el saldo pero a través de arduino, sin embargo, no logro comprender en qué sector está almacenado el saldo, no tengo la llave de cifrado para poder acceder a los bloques de la tarjeta, pero tampoco entiendo cómo se puede entonces extraer el saldo, Estaría agradecido si me puedes dar una mano. 

Gracias

**Comment by zqu4rtz** [comment]
Hola, 

Este código no contiene ninguna llave privada para leer los bloques de memoria de la tarjeta. La forma de leer el balance es a través del protocolo [ADPU](https://es.wikipedia.org/wiki/Application_Protocol_Data_Unit_(electr%C3%B3nica)), utilizando una serie de comandos y respuestas recibidos por la tarjeta. Este protocolo te permite invocar ciertos servicios personalizados de la tarjeta, entre ellos la lectura del número, saldo e historial de transacciones.  

Los comandos enviados a la tarjeta los puedes encontrar aquí: 

https://github.com/zqu4rtz/FlipperApp-TuLlave/blob/main/lib/tullave/protocols/tullave_poller.c

Espero que esto te ayude en tu proyecto  😄

**Comment by rebelskvll** [comment]
Ahh, claro. Así nunca iba a dar con el saldo de la tarjeta. Me leo la documentación entonces. 
Te agradezco tu tiempo y ayuda.
